load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_test")

cc_test(
    name = "testAll",
    srcs = ["test.cpp", "inputs.h"],
    deps = [
        "//Solutions/CPP/soln:14",
        "@com_google_googletest//:gtest_main",
    ],
)