
cc_library(
    name = "hello",
    srcs = ["hello/hello.cc"],
    hdrs = ["hello/hello.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "QuickFind",
    srcs = ["QuickFind/unionFind.cc"],
    hdrs = ["QuickFind/unionFind.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "QuickUnion",
    srcs = ["QuickUnion/unionFind.cc"],
    hdrs = ["QuickUnion/unionFind.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "QuickUnionRank",
    srcs = ["QuickUnionRank/unionFind.cc"],
    hdrs = ["QuickUnionRank/unionFind.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "QuickUnionPathCompression",
    srcs = ["QuickUnionPathCompression/unionFind.cc"],
    hdrs = ["QuickUnionPathCompression/unionFind.h"],
    visibility = ["//visibility:public"],
)
