
cc_library(
    name = "hello",
    srcs = ["hello/hello.cc"],
    hdrs = ["hello/hello.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "QuickFind",
    srcs = ["UnionFind/QuickFind/unionFind.cc"],
    hdrs = ["UnionFind/QuickFind/unionFind.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "QuickUnion",
    srcs = ["UnionFind/QuickUnion/unionFind.cc"],
    hdrs = ["UnionFind/QuickUnion/unionFind.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "QuickUnionRank",
    srcs = ["UnionFind/QuickUnionRank/unionFind.cc"],
    hdrs = ["UnionFind/QuickUnionRank/unionFind.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "QuickUnionPathCompression",
    srcs = ["UnionFind/QuickUnionPathCompression/unionFind.cc"],
    hdrs = ["UnionFind/QuickUnionPathCompression/unionFind.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "QuickUnionRankPathCompression",
    srcs = ["UnionFind/OptimizedUnionbyRankPathCompression/unionRankPathCompression.cc"],
    hdrs = ["UnionFind/OptimizedUnionbyRankPathCompression/unionRankPathCompression.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "DFSvalidPath",
    srcs = ["DFS/validPath/dfsValidPath.cc"],
    hdrs = ["DFS/validPath/dfsValidPath.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "DFSallPaths",
    srcs = ["DFS/allPaths/dfsAllPaths.cc"],
    hdrs = ["DFS/allPaths/dfsAllPaths.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "BFSvalidPath",
    srcs = ["BFS/validPath/bfsValidPath.cc"],
    hdrs = ["BFS/validPath/bfsValidPath.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "BFSallPaths",
    srcs = ["BFS/allPaths/bfsAllPaths.cc"],
    hdrs = ["BFS/allPaths/bfsAllPaths.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "BFSfindLevel",
    srcs = ["BFS/levelOrderTraversal/findLevel.cc"],
    hdrs = ["BFS/levelOrderTraversal/findLevel.h"],
    visibility = ["//visibility:public"],
)
