
cc_library(
    name = "hello",
    srcs = ["hello/hello.cc"],
    hdrs = ["hello/hello.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "QuickFind",
    srcs = ["UnionFind/QuickFind/unionFind.cc"],
    hdrs = ["UnionFind/QuickFind/unionFind.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "QuickUnion",
    srcs = ["UnionFind/QuickUnion/unionFind.cc"],
    hdrs = ["UnionFind/QuickUnion/unionFind.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "QuickUnionRank",
    srcs = ["UnionFind/QuickUnionRank/unionFind.cc"],
    hdrs = ["UnionFind/QuickUnionRank/unionFind.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "QuickUnionPathCompression",
    srcs = ["UnionFind/QuickUnionPathCompression/unionFind.cc"],
    hdrs = ["UnionFind/QuickUnionPathCompression/unionFind.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "QuickUnionRankPathCompression",
    srcs = ["UnionFind/OptimizedUnionbyRankPathCompression/unionRankPathCompression.cc"],
    hdrs = ["UnionFind/OptimizedUnionbyRankPathCompression/unionRankPathCompression.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "DFS",
    srcs = ["DFS/dfs.cc"],
    hdrs = ["DFS/dfs.h"],
    visibility = ["//visibility:public"],
)
